### ISSUE TITLE
mac_pstree binary output

### ISSUE THREAD

**Issue by gleeda** [volatilityfoundation/volatility#158]
see here:

https://twitter.com/AusDannis/status/550899228365447168

http://i.imgur.com/6APVzTl.png

**Comment by dannisAr** [comment]
Thankyou gleeda for redirecting me.

The profile in use when this occured was: https://github.com/volatilityfoundation/profiles/tree/master/Mac/10.9/x64

**Comment by atcuno** [comment]
Can you please run both mac_tasks and mac_pslist and see if you get a
better process listing? Also can you see if the output of mac_lsmod
looks reasonable?

Which acquisition tool did you use ?

**Comment by dannisAr** [comment]
Hi atcuno, thanks for getting back to me quickly.

I used OSXPMem for the acquisition formatted in mach o. 

Here is a screengrab of some of the weird process listings on mac_pslist and mac_tasks.
http://i.imgur.com/fAJ98Us.png
Ls mod came up fine with no binary outputs.

Thanks!

**Comment by atcuno** [comment]
Hey,

Thanks for the screenshot. It looks like the tasks data structure is
partially corrupt (hence weird values) vs the pslist data structure
which is in tact. Unfortunately, Mac acquisition tools (all of them that
we have tested) have a strong chance of corrupting either/both of the
pslist or the tasks list.

You can change pstree to use pslist instead of tasks by applying the
following patch (based off latest Volatility pull):

------

diff --git a/volatility/plugins/mac/pstree.py
b/volatility/plugins/mac/pstree.py
index bd9a811..f320300 100644
--- a/volatility/plugins/mac/pstree.py
+++ b/volatility/plugins/mac/pstree.py
@@ -24,9 +24,9 @@
 @organization:
 """

-import volatility.plugins.mac.pstasks as pstasks
+import volatility.plugins.mac.pslist as pslist

-class mac_pstree(pstasks.mac_tasks):
+class mac_pstree(pslist.mac_pslist):
     """ Show parent/child relationship of processes """

     def render_text(self, outfd, data):


-----

If you have problems applying the patch just let me know and I can send
you the file to replace.

**Comment by dannisAr** [comment]
Hi Atcuno,

Thanks for this. Have a nice weekend.

I really appreciate it.
