### ISSUE TITLE
Win7 64bit Virtual to Physical Address issue (memmap plugin)

### ISSUE THREAD

**Issue by 0xredskull** [volatilityfoundation/volatility#160]
Virtual to Physical Address works for Win7SP1x86 and WinXP
Win7-32 bit lsass.exe (pid 528)
$ vol.py -f win7.img --profile=Win7SP1x86 -p 528 dlllist | grep 'kernel32.dll'
Volatility Foundation Volatility Framework 2.4
0x76dc0000    0xd4000     0xffff C:\Windows\system32\kernel32.dll
$ vol.py -f win7.img --profile=Win7SP1x86 -p 528 memmap | egrep '^0x76dc0000'
Volatility Foundation Volatility Framework 2.4
0x76dc0000 0x25fb5000     0x1000       0x1c0000

Win7-64 bit lsass.exe (pid 536)
$ vol.py -f win7-64.img --profile=Win7SP1x64 -p 536 dlllist | grep 'kernel32.dll'
Volatility Foundation Volatility Framework 2.4
0x0000000076f90000           0x11f000             0xffff C:\Windows\system32\kernel32.dll
$ vol.py -f win7-64.img --profile=Win7SP1x64 -p 536 memmap | egrep '^0x0000000076f90000'
Volatility Foundation Volatility Framework 2.4
No matching output for virtual address

**Comment by iMHLv2** [comment]
Hello....I would suggest going into volshell and seeing if the address is actually valid (i.e. in physical memory rather than the page file etc):

```
$ vol.py -f win7-64.img --profile=Win7SP1x64 -p 536 volshell 
>>> db(0x0000000076f90000)
```

If that tells you the address is invalid, then 0x0000000076f90000 is paged to disk. The memmap plugin only shows what's valid. If it shows an MZ header as you would expect to see if its the base address of kernel32.dll then try modifying your grep statement....for example maybe it shows as 0x76f90000 or 0x76F90000.
