### ISSUE TITLE
No valid DTB found - Win 8/8.1/2012 64bit vmem > 4GB

### ISSUE THREAD

**Issue by Sebastienbr** [volatilityfoundation/volatility#193]
Conditions for the problem:
- Vmem memory dump 
- Win 8/8.1/2012 64bit 
- Dump is > 4GB
- Vmss metadata file is present
- Vmware metadata fill the gap between 0xC0000000 and 0x100000000

During the voting round, FileAddressSpace and VMWareMetaAddressSpace are correctly loaded but AMD64PagedMemory failed to load (no valid DTB found). 

If I manually pad the Win 8/8.1/2012 64bit vmem memory dump (between 0xC0000000 and 0x100000000) and I rename them to .dd (to avoid loading the vmem address space), FileAddressSpace and AMD64PagedMemory are correctly loaded and my dump can be analysed.

Any ideas why dtb is not found when VMWareMetaAddressSpace is used?
https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/addrspaces/paged.py#L68

Thanks again for your help,

Sebastien

**Comment by Sebastienbr** [comment]
A little bit more about this problem.

In my test memory dump, the 'Idle' process is located in the offset 0x1AE000000. However, when the VMWareMetaAddressSpace is loaded, volatility stop to read data at 0xC0000000 here [1] so the Idle process is never found. 

The range between 0xC0000000 and 0x100000000 is supposed to be handled by the vmem address space but the

```
self.obj_vm.read(offset, constants.SCAN_BLOCKSIZE) [1] 
````
return None when reading 0xC0000000.

Any suggestions? I will continue to dig into this problem and will keep you updated :-)

Thanks

[1] https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/overlays/basic.py#L224

**Comment by Sebastienbr** [comment]
I don't know if it's a good solution but if I replace [1] with a zread, it works.

```
self.obj_vm.zread(offset, constants.SCAN_BLOCKSIZE)
```


[1] https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/overlays/basic.py#L224

**Comment by iMHLv2** [comment]
This sounds very similar to the QEMU issue https://github.com/volatilityfoundation/volatility/issues/10. In both cases, the DTB is located outside of the first "run" of physical memory and using read() rather than zread() prevents the DTB scanner from ever getting to the later runs. I think the fix is fine. Raw memory images would never have this problem and the worst thing that can happen is it will just take longer to scan from 0xC0000000 to 0x1AE000000 (we'll be getting back 5 MB chunks of 0's and then scanning it) however I suppose taking a bit longer and eventually working is better than aborting and not working at all.

**Comment by iMHLv2** [comment]
Hmm, actually...just switching read() to zread() may not be sufficient. If a DTB is not actually present in the file (due to anti-forensics, or faulty memory capture), then the DTB scanner will go on forever since zread() masks failures and always returns 0's. We may need to incorporate an additional check that knows when zread() has past the end of the file. 

In the meantime, does the psscan and --dtb switch work for you? (as described in #10)?

**Comment by Sebastienbr** [comment]
Good point! 

Here's a suggestion for [basic.py]. Do you think it can solve the problem?

```
@@ -211,6 +211,8 @@ class VolatilityDTB(obj.VolatilityMagic):
     def generate_suggestions(self):
         offset = 0
         data = self.obj_vm.read(offset, constants.SCAN_BLOCKSIZE)
+        last_range_start, last_range_size = sorted(self.obj_vm.get_available_addresses())[-1]
+        maxOffset = last_range_start + last_range_size
         while data:
             found = data.find(str(self.obj_parent.DTBSignature), 0)
             while found >= 0:
@@ -221,7 +223,10 @@ class VolatilityDTB(obj.VolatilityMagic):
                 found = data.find(str(self.obj_parent.DTBSignature), found + 1)

             offset += len(data)
-            data = self.obj_vm.read(offset, constants.SCAN_BLOCKSIZE)
+            if offset < maxOffset:
+                data = self.obj_vm.zread(offset, constants.SCAN_BLOCKSIZE)
+            else:
+                data = None
```

Thanks, 

Sebastien

[basic.py]: https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/overlays/basic.py

**Comment by iMHLv2** [comment]
Looks good to me. Just applied something very similar - let me know if you see any issues with it.

**Comment by Sebastienbr** [comment]
Thank you Michael :)
