### ISSUE TITLE
Performance problem - memmap and unified output

### ISSUE THREAD

**Issue by Sebastienbr** [volatilityfoundation/volatility#205]
Hi,

I have a 512MB Windows 7 x86 memory dump and found a performance issue with memmap and the unified output. 

When I run this command, it takes 2 minutes to run:

```
python vol.py -f win732.vmem --profile=Win7SP1x86 memmap
```

However, if I run memmap with the unified output, I takes 3 days to finish:

```
python vol.py -f win732.vmem --profile=Win7SP1x86 memmap --output=json --output-file=test.json
```

Any ideas how to accelerate the unified output of [1] ?

Thanks!

[1] https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/taskmods.py#L268

**Comment by gleeda** [comment]
hrmmm not sure why it would take *that* long.  @ikelos any thoughts?

**Comment by ikelos** [comment]
Hiya, so it will pass over the data twice, rather than once (because it populates the data, then runs through it all to render it), but I suspect the killer here will be the size of the data and strings being thrown around in memory.  So the TreeGrid structure will have to keep a copy of all the data, then we construct another python list to contain all the data in the rows, and then finally we serialize all that into a JSON string.  If the data size is significant, that'll cause swapping, and the swapping could easily inflate the execution time to several days.

The best/easiest way of testing this would be run to it with the quick text output plugin, and then by commenting out the render_text function from the plugin.  The timings of those will show us whether it's memory or something else in the tree building process that's causing the problem...

**Comment by Sebastienbr** [comment]
Thanks Mike! 
 
My memmap data has approximately 1 280 000 rows. I did have a look a couple days ago when volatility was processing my memory dump and the python process was only consuming 1.5 GB of RAM. My workstation have a lot of RAM: I don't think volatility was swapping data. 

I have done a trace on the code

```
python -m trace -t vol.py -f win732.vmem --profile=Win7SP1x86 memmap --output=json --output-file=test.json
```

and I think I have found the problem. Let me know if it make sense because I have not read and understood the entire TreeGrid code :-)

The performance problem seems to be in the [children function]. Each time a node is [append], the [children function] loop over all the nodes. With more than one million nodes, I think it takes a lot of time to iterate through each node every time a new node is added. 

Here's the part of the trace where I have notice the problem:

```
__init__.py(150):                 parent_index = min(len(prev_nodes), level)
__init__.py(151):                 parent = prev_nodes[parent_index - 1] if parent_index > 0 else None
__init__.py(152):                 treenode = self._append(parent, item)
 --- modulename: __init__, funcname: _append
__init__.py(196):         children = self.children(parent)
 --- modulename: __init__, funcname: children
__init__.py(169):         return [node for node, _ in self._find_children(node)]
 --- modulename: __init__, funcname: _find_children
__init__.py(176):         children = self._children
__init__.py(177):         try:
__init__.py(178):             if node is not None:
__init__.py(183):         return children
__init__.py(169):         return [node for node, _ in self._find_children(node)]
__init__.py(197):         return self._insert(parent, len(children), values)

[...]

__init__.py(150):                 parent_index = min(len(prev_nodes), level)
__init__.py(151):                 parent = prev_nodes[parent_index - 1] if parent_index > 0 else None
__init__.py(152):                 treenode = self._append(parent, item)
 --- modulename: __init__, funcname: _append
__init__.py(196):         children = self.children(parent)
 --- modulename: __init__, funcname: children
__init__.py(169):         return [node for node, _ in self._find_children(node)]
 --- modulename: __init__, funcname: _find_children
__init__.py(176):         children = self._children
__init__.py(177):         try:
__init__.py(178):             if node is not None:
__init__.py(183):         return children
__init__.py(169):         return [node for node, _ in self._find_children(node)]
__init__.py(169):         return [node for node, _ in self._find_children(node)]
__init__.py(197):         return self._insert(parent, len(children), values)

[...]

__init__.py(150):                 parent_index = min(len(prev_nodes), level)
__init__.py(151):                 parent = prev_nodes[parent_index - 1] if parent_index > 0 else None
__init__.py(152):                 treenode = self._append(parent, item)
 --- modulename: __init__, funcname: _append
__init__.py(196):         children = self.children(parent)
 --- modulename: __init__, funcname: children
__init__.py(169):         return [node for node, _ in self._find_children(node)]
 --- modulename: __init__, funcname: _find_children
__init__.py(176):         children = self._children
__init__.py(177):         try:
__init__.py(178):             if node is not None:
__init__.py(183):         return children
__init__.py(169):         return [node for node, _ in self._find_children(node)]
__init__.py(169):         return [node for node, _ in self._find_children(node)]
__init__.py(169):         return [node for node, _ in self._find_children(node)]
__init__.py(197):         return self._insert(parent, len(children), values)

[...]
```

Thanks!

[children function]: https://github.com/volatilityfoundation/volatility/blob/master/volatility/renderers/__init__.py#L169

[append]:
https://github.com/volatilityfoundation/volatility/blob/master/volatility/renderers/__init__.py#L152

**Comment by ikelos** [comment]
Hmmmm, that was rather daft of me, wasn't it?  Sorry about that, could you please try the code in branch issue-205 for me, and let me know if that helps speed it up (and how slow it is, in relation to the standard render_text)?  Thanks!

**Comment by Sebastienbr** [comment]
Thanks for the modification!

Here's the run time for memmap:

- standard render_text (no unified output): 3 minutes 
- quick: 6 minutes
- text: 3 minutes
- json: 8 hours 40 minutes
- sqlite: 1 day, 3 hours

The populate phase is much faster but there's still an issue with the render phase.

Thanks!

**Comment by ikelos** [comment]
Hmmm,

Thanks that running information is very interesting.  My guess is still memory over usage in the json module. I'm not sure about the sqlite one, I'll check that and see if we're doing transactions or not (individual commits could easily slow everything down).  I don't know that we'll be able to solve all the issues, but I think there's still a bit more we can do to optimize things...

**Comment by ikelos** [comment]
Right,

I've just commited a change (to both issue-205 and master) making use of transactions in sqlite, rather than automatically comitting after each insert statement.  That should provide an extremely significant speed increase (on a simple test, from 284 seconds to 15 seconds, so about 20x increase).  The json issue might be harder to spot, but I'll leave this open so that people can find it...

**Comment by ikelos** [comment]
Ok,

So after further testing and reading around, it turns out that json serlization is *really* slow, and that the built-in json serializer for python is possibly the slowest example of one you can get. So we'd either have to package an additional python package just for json, or allow people to use it and have most of them miss out on it, and in either case it would still take a ridiculously long time to deal with 100,000 entries...

I don't intend to spend much more time on this.  ujson will speed it up, and I've commited a patch that will opportunistically make use of ujson, but whichever way you cut it, json output will be slow. If anyone finds a better way of dealing with this, feel free to comment and reopen.

**Comment by gleeda** [comment]
Thank you for taking the time to investigate this, @ikelos :-)

**Comment by Sebastienbr** [comment]
Thank you Mike for your help! I appreciate!

Here's the new results:
- sqlite: 22 hours, 13 minutes
- ujson: 19 hours

I might have found something to improve the speed. I have implemented a new render class called QuickSqliteRenderer. With this render I am able to generate the sqlite file with more than a million rows in 4 minutes :)

However I am not an expert in the render classes and if you have some spare time, I would like to have your opinion on my code. Let me know what's the best way to share it (i.e: pull request or paste new code here).

Thanks in advance!

Sebastien

**Comment by ikelos** [comment]
Hiya Sebastian, I'm very interested to see what you did differently.  There's an executemany function that I was toying with, but reworking the visitor to get into effectively an iterator looked like it would be a pain to achieve...

Probably a pull request would be the best way to check out the new code, although either will work. Thanks!
