### ISSUE TITLE
Legacy VGA area

### ISSUE THREAD

**Issue by Phaeilo** [volatilityfoundation/volatility#223]
I'm currently developing an adressspace using `AbstractDiscreteAllocMemory`. I can provide most of physical memory, but not the legacy VGA area from `0xa000` to `0xbffff`. When using Windows profiles, AMD64 and IA32 try to perform a `read` of the first 10 megabytes of memory. If the VGA hole is present they fail to initialize. However, if I redirect this `read` to `zread`, AMD64 and IA32 will initialize just fine. I'm not too happy with this workaround.

Is this an issue with AMD64 and IA32? Maybe they should use `zread` when reading the 10 megabytes.

**Comment by iMHLv2** [comment]
Do you happen to know where in the code it reads 10 MB? We recently patched the DTB finding function to use zread instead of read. Are you using the latest code base with the following changes?

https://github.com/volatilityfoundation/volatility/commit/a44ca3aac310de74ee82e007aa4036a477ef1570
https://github.com/volatilityfoundation/volatility/commit/36b7c77bdf0301d41e4aea20c0a189c4686a128b

**Comment by Phaeilo** [comment]
I was using Volatility 2.4. I fetched the latest version from Github and can confirm that the problematic `read` was changed to `zread`.

However, AMD64 and IA32 on Windows profiles will not find a DTB when I'm using my adressspace. If I create a raw memory image and load it into Volatility without my adressspace, DTB detection works fine. I have verified, that a `zread` of the first 10 megabytes of memory using my adressspace will return exactly the same data as contained in the raw memory image.

Have there been some changes to adressspaces since 2.4 that I'm missing?

**Comment by iMHLv2** [comment]
Hmm, not that I can think of. Are you setting/using the same profile between AMD64/IA32 and your AS? The profile makes a big difference, because the offsets to _EPROCESS.ImageFileName and _EPROCESS.Pcb are incorporated into the DTB-finding code. 

You can also set the DTB on command-line, like this:

```
$ python vol.py -f FILE -p PROFILE --dtb=VALUE
```

If you manually set the DTB, does your AS work? If there are still issues, I'd suggest printing some values in the DTB finder: 

https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/overlays/basic.py#L209

Also, make sure to implement get_available_addresses() in your AS, because the DTB finder calls that method: 

https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/overlays/basic.py#L214

**Comment by Phaeilo** [comment]
Implementing `get_available_addresses` solved my problem. Automatic DTB detection now works fine with my AS and Windows profiles. I made the incorrect assumption that `AbstractDiscreteAllocMemory` already implemented this method using the data from my `get_available_allocs` implementation.

**Comment by iMHLv2** [comment]
Awesome! What's type of address space are you developing? Just FYI, we announced the 2015 plugin contest: http://www.volatilityfoundation.org/#!2015/c1qp0

**Comment by Phaeilo** [comment]
I'm extracting memory contents from network traffic. It will be published in the next few months. Good to know that there will be plugin contest again!

**Comment by iMHLv2** [comment]
Cool man....let me know if you run into any other issues. Memory contents from a pcap sounds interesting!
