### ISSUE TITLE
Issue Analyzing Windows 8.1 x64 Dumps

### ISSUE THREAD

**Issue by MrAnde7son** [volatilityfoundation/volatility#256]
I've been trying to analyze Windows 8.1 memory dumps lately with no luck.
I tried many acquisition tools including RAM Capturer, DumpIt, Memoryze and also Hibernation file and crash dump.
I keep getting "No suitable address space mapping found" error, like the profile used (Win8SP1x64 )  does not match.
I tried using both volatility 2.5 and 2.4 and both failed to analyze the memory dump.

**Comment by iMHLv2** [comment]
Hello...are you using the standalone binaries (i.e. volatility_2.5.exe) or are you using the Python source package (i.e. vol.py)?

**Comment by ltamar** [comment]
ן used Python source of both 2.4 and 2.5 and also 2.4 binary.

**Comment by iMHLv2** [comment]
OK, couple of questions/comments: 

* For 64-bit Win8 and above, you need the distorm3 python module installed (if you're using the python source method). See https://github.com/volatilityfoundation/volatility/wiki/Windows-8-2012. 

* I would recommend sticking with 2.5 source (latest from github) or the 2.5 binary for testing - there's quite a bit of "new" stuff in 2.5 that would make it more reliable in these situations. If you use the 2.5 binary, you don't need to install distorm3 because its packaged into the binary already.

* The "No suitable address space mapping found" typically indicates an invalid/corrupt memory dump. Dumpit and Memoryze are two of the worst tools to use to capture memory. Additionally, we don't support hibernation files from Windows 8..so that will inevitably fail. The crash dump is probably the most reliable method out of your current options, however it depends on how you collected the crash dump. For example, Volatility only supports "complete" crash dumps - not "kernel" dumps or "minidumps" etc. 

How did you collect the crash dump?

**Comment by ltamar** [comment]
Thanks for the reply.
- Distorm3 is installed on my machine.
- What are your thoughts about RAM Capturer by Belksoft?
- Good to know there is no support for hibernation file, I wasn't sure.
- I forced crash by key stroke of death. I'm not sure about the configuration and I don't have access to the machine atm. I will give it a try and see if it works.
Thanks!

**Comment by ltamar** [comment]
Hey, 

I changed the configuration of the crash dump from 'automatic' to 'complete', and now instead of "No suitable address space mapping found", I get no output at all.
I'm using standalone volatility 2.5 version, Win8SP1x64 profile.
Any idea what's wrong?
BTW, volatility foundation site says it does support windows 8.1 hibernation file.

**Comment by ltamar** [comment]
I'm able to analyze memory dump acquired with RAM Capturer by specifying the kdbg offset, but crash dump still fails.

**Comment by iMHLv2** [comment]
Could you run the crashinfo plugin against your crash dump? It will output some metadata worth examining to see if there's any thing strange going on. 

Is Windbg able to open your crash dump (windbg.exe -z memdump.dmp)?

**Comment by aungthurhahein** [comment]
@ltamar  About Windows 8.0/8.1 hibernation file, volatility team is targeting it as milestone for ver. 2.5 but it is not still supported.If you have a hand on monsols Hibr2dmp, you can decompress Windows 8 hiberfil.sys to raw dumps.

https://twitter.com/AtrHein/status/657403888669102080
https://github.com/volatilityfoundation/volatility/issues/176

**Comment by ltamar** [comment]
@iMHLv2 I ran crash info against the crash dump and it looked fine, will post the output here once I have access to the machine again.

@aungthurhahein I see. Thanks!

**Comment by iMHLv2** [comment]
Hi @aungthurhahein, thanks for chiming in. Were you able to verify that Hibr2dmp decompressed Win 8 hibernation files successfully? I've heard mixed results, so just wanted to confirm.

**Comment by iMHLv2** [comment]
Hi @ltamar, sounds good...we'd be interested to see the crashinfo output that you got. Also, please try to open the crash dump in Windbg - that will be a good test case for troubleshooting purposes. 

Since you were able to analyze the dump created by RAM Capturer, are you thinking the current issue is just with the crash dump file format?

**Comment by aungthurhahein** [comment]
@iMHLv2 I can't verify about success of Hibr2dmp for Windows 8 since I don't have personal xp with moonsols paid version. However, it seems like that's the only option to decompress win8 hiberfil.sys at this moment.

**Comment by ltamar** [comment]
@iMHLv2 Yeah, it seems like RAM Capturer is the only memory acquisition tool that support Windows 8.1 out of the ones I used.
I will also try to debug it with Windbg to see if it reveals anything interesting.
Thanks!

Here's the output of crashinfo ran against the crash dump:
_DMP_HEADER64:
 Majorversion:         0x0000000f (15)
 Minorversion:         0x00002580 (9600)
 KdSecondaryVersion    0x00000041
 DirectoryTableBase    0x001aa000
 PfnDataBase           0xfffffa8000000000
 PsLoadedModuleList    0xfffff80212952630
 PsActiveProcessHead   0xfffff802129383c0
 MachineImageType      0x00008664
 NumberProcessors      0x00000004
 BugCheckCode          0x000000e2
 KdDebuggerDataBlock   0xfffff8021291f530
 ProductType           0x00000001
 SuiteMask             0x00000110
 WriterStatus          0x45474150
 Comment               PAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGE
 DumpType              BitMap Dump
 SystemTime            2015-11-08 07:19:57 UTC+0000
 SystemUpTime          0:53:39.516940

Physical Memory Description:
Number of runs: 8
FileOffset    Start Address    Length
00002000      00001000         00090000
00092000      00100000         00002000
00094000      00103000         0018f000
00223000      00296000         bd9a8000
bdbcb000      be0bb000         1c51c000
da0e7000      da740000         00786000
da86d000      dbaff000         00001000
da86e000      100000000         f9080000
1d38ed000      1f907f000

**Comment by gleeda** [comment]
@ltamar out of curiosity, could you apply this patch and see if you get anything different from your crash dump?  Someone else on irc said that they had an issue with Win 8.1 x64 crash dumps and that this patch fixed it.  May have been something totally unrelated though, but just in case:

[crash.txt](https://github.com/volatilityfoundation/volatility/files/30886/crash.txt)

You can apply the patch like so (from linux/mac) from within the root directory of volatility: 
```
patch -p1 < crash.txt
```

**Comment by gleeda** [comment]
@ltamar do you have any update on this?

**Comment by ltamar** [comment]
Oh sorry I haven't seen your comment.
I will apply the patch and inform you.
Thanks!

**Comment by nirizr** [comment]
reminding @ltamar to report on this :)

**Comment by ltamar** [comment]
Sorry for the delay, I was unavailable. Will update later today :)

**Comment by ltamar** [comment]
@gleeda issue remains post patch, so I guess it's unrelated.
@nirizr
