### ISSUE TITLE
exception while using yarascan

### ISSUE THREAD

**Issue by hadar0x** [volatilityfoundation/volatility#257]
While using yarascan, i encountered the following error:

user@linux:~/Desktop/volatility$ python vol.py -f /home/user/VMs/Win7x86/Windows7-970e1015.vmem --profile=Win7SP0x86  yarascan -y ~/Desktop/processhacker.yar
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/user/Desktop/volatility/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/home/user/Desktop/volatility/volatility/plugins/malware/malfind.py", line 331, in render_text
    for o, addr, hit, content in data:
  File "/home/user/Desktop/volatility/volatility/plugins/malware/malfind.py", line 294, in calculate
    for p in process_mem:
  File "/home/user/Desktop/volatility/volatility/plugins/malware/malfind.py", line 235, in _scan_process_memory
    for hit, address in scanner.scan():
  File "/home/user/Desktop/volatility/volatility/plugins/malware/malfind.py", line 134, in scan
    for match in BaseYaraScanner.scan(self, vad.Start, vad.Length):
  File "/home/user/Desktop/volatility/volatility/plugins/malware/malfind.py", line 114, in scan
    for moffset, _name, _value in match.strings:
AttributeError: 'str' object has no attribute 'strings'

Tried re-installing and also to use volatility directly from its directory. Didn't help :(

**Comment by iMHLv2** [comment]
Hello - can you tell me what version of Yara and Yara Python you have installed...and also how you installed them? 

We recommend using Yara from https://plusvic.github.io/yara. In other words, try not to install it from pip or easy_install or other package managers.

**Comment by cloughrm** [comment]
+1, having the same issue with volatility 2.4/2.5, yara 3.4.0, yara-python 3.4.0. Investigating now.

**Comment by cloughrm** [comment]
Looking at the latest Yara documentation, it looks to me like it is being called incorrectly in malfind.py.

According to http://yara.readthedocs.org/en/latest/yarapython.html
```
with open('/foo/bar/my_file', 'rb') as f:
  matches = rules.match(data=f.read())
```

The current malfind plugin is attempting to iterate over the rule.match function, this returns a string instead of the expected dictionary containing strings.
https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/malware/malfind.py#L110

**Comment by cloughrm** [comment]
I have a PR in my own fork, let me know what you think:
https://github.com/ts-labs/volatility/pull/1

**Comment by iMHLv2** [comment]
Hmm, I won't lie guys, I'm super confused. According to the documentation link (http://yara.readthedocs.org/en/latest/yarapython.html) it says: 

```
The match method returns a list of instances of the class Match. Instances of this class have the same attributes as the dictionary passed to the callback function.
```

If I download 3.4.0 from https://github.com/plusvic/yara/archive/v3.4.0.zip and install Yara and then Yara-Python from inside that zip file, I get this:

```
# yara -v
yara 3.4.0
```

And this shows me the full path to the Yara library: 

```
# python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
>>> help(yara)
Help on module yara:

NAME
    yara - This module allows you to apply YARA rules to files or strings.

FILE
    /usr/local/lib/python2.7/dist-packages/yara.so

>>> quit()
```

Which we can then look in the directory for the egg and get the version:

```
# grep Version /usr/local/lib/python2.7/dist-packages/yara_python-3.4.0.egg-info 
Metadata-Version: 1.0
Version: 3.4.0
```

If you then try using the example on the yara-python repository (https://github.com/plusvic/yara-python), you'll see this:

```
>>> import yara
>>> rule = yara.compile(source='rule foo {strings: $a = "lmn" condition: $a}')
>>> matches = rule.match(data='abcdefgjiklmnoprstuvwxyz')
>>> matches
[foo]
>>> type(matches[0])
<type 'yara.Match'>
>>> matches[0].strings
[(10L, '$a', 'lmn')]
>>> matches[0].rule
'foo'
```

So that tells me the match() API does in fact return a list of `Match` class instances and that the `strings` and `rule` attributes are both as expected. 

Can you do what I did above and paste your output?

**Comment by hadar0x** [comment]
Upgraded my yara to 3.4 and now it works (volatility 2.5)

**Comment by iMHLv2** [comment]
@hadar0x - any idea what version you had previously installed? It must have been quite old, because AFAIK the API hasn't changed in a couple years. 

@cloughrm - still not sure what's going on with yours....

**Comment by cloughrm** [comment]
Figured out what was happening, I am using virtualenv and had multiple versions of the python-yara packaged installed, and python was grabbing the old version (1.7.7). Thanks for your help @iMHLv2, looks like this can be closed.
