### ISSUE TITLE
tool request: check integrity memory dump

### ISSUE THREAD

**Issue by fpusersuggest** [volatilityfoundation/volatility#275]
It would be very useful a tool to check the memory dump integrity to avoid to open issues that depend on memory dump corruption.

**Comment by iMHLv2** [comment]
I'm going to mark this as won't fix, since its not directly related to volatility, but I'd definitely encourage you to post the request on vol-users (http://lists.volatilesystems.com/mailman/listinfo/vol-users) and try to see if people are interested in working on this with you. A lot of corruption we see is related to smearing (i.e. slowness or poor error checking during acquisition) or failure to acquire a large part of non-paged memory, both of which will be quickly determined by a simple pslist. Unfortunately from volatility's perspective alone, other types of integrity checks are difficult, since volatility only knows one side of the story (i.e. what you give it) rather than what's actually in RAM of the machine - so this project may involve some coordination between a memory acquisition utility and volatility.
