### ISSUE TITLE
Vmware ESXi 5.5 - Windows 2012 imageinfo no suggestion

### ISSUE THREAD

**Issue by kgehrke2009** [volatilityfoundation/volatility#281]
I am having an issue trying to get imageinfo working.  I took a snapshot of a Windows 2012R2 server and selected the "save memory with snapshot" option as I have done with Windows 2008 servers in the past.

Running Volatility 2.5, my command is volatility.exe -f <filename.vmsn> imageinfo

Windows 2008R2 8GB memory files are fine.

Running against a Windows 2012R2 16GB RAM snapshot file , volatility imageinfo returns no results.

volatility says it supports .vmss and .vmsn files and it works against 2008 .vmsn files.  I have tried 2 snapshots from 2 separate servers to rule out a corrupt memory file.

**Comment by iMHLv2** [comment]
Hello - couple of questions for you: 

1) For the 2012R2 do you also have a vmem present in the directory? If so, point volatility at the vmem and just make sure the vmss or vmsn are still in the directory when you do so. 

2) Can you run the vmwareinfo plugin against any of the files (vmss, vmsn, or vmem)? 

3) Does the kdbgscan plugin return any results? I would run it as "kdbgscan --profile=Win2012R2x64" since you already know the profile.

**Comment by kgehrke2009** [comment]
I fixed it.  I ran the --profile option and that got me to the KdCopyDataBlock which I used that for the --kdbg and I was able to properly read the .vmsn file.
