### ISSUE TITLE
Virtualbox dump format version change

### ISSUE THREAD

**Issue by bluec0re** [volatilityfoundation/volatility#287]
The version of the vbox dumpvmcore file format has changed.

The new value is 0x00010003 and currently seems to be compatible to the previous format.

**Comment by iMHLv2** [comment]
Hi @bluec0re. Any chance you could share a memory dump from a test/barebones VM on your vbox that has this new version number?

**Comment by bluec0re** [comment]
Here is a dump: https://mega.nz/#!XM4FSYCI!Gzkn8bhFihX72tb9SB0vMjJdrwCOioHFJ0Oy5NCt5zg

but it seems that the value now is 0x10005 (Vbox 5.1.6) (file offset 0x000002c0)

**Comment by iMHLv2** [comment]
Great, thanks. See if 107cd7360ff20b184ee769feecddd033b3fe4d7a fixes the issue for you. It seems to work over here. I just masked off the lower bits instead of doing an exact match against 0x00010000. That should keep it working when future versions increase. 

```
$ python vol.py -f ~/Desktop/foo.dump vboxinfo 
Volatility Foundation Volatility Framework 2.5
Magic: 0xc01ac0de
Format: 0x10005
VirtualBox 5.1.6 (revision 110634)
CPUs: 1

FileOffset Memory Offset Size      
    0x2528           0x0 0x10000000
0x10002528    0xe0000000  0x1300000
0x11302528    0xf0400000   0x400000
0x11702528    0xf0800000     0x4000
0x11706528    0xffff0000    0x10000
```

Please reopen if that doesn't work for you.
