### ISSUE TITLE
Version2.5 in CentOS6.6 can not list the new linux profile

### ISSUE THREAD

**Issue by JackNine** [volatilityfoundation/volatility#321]
Hi, I have made a ubuntu12.01 profile with volatility2.5. I can use the profile rightly in Ubuntu OS. When I want to do the same thing in CentOS6.6 . I can not find the profile with python vol.py --info |grep Linux. Could someone help me?

[root@localhost linux]# pwd
/volatility-2.5/volatility-master/volatility/plugins/overlays/linux
[root@localhost linux]# ls
elf.py   __init__.py   linux.py    Ubuntu12.01.zip------------------->this is the profile I added
elf.pyc  __init__.pyc  linux.pyc

[root@localhost volatility-master]# python vol.py  --info |grep Linux
Volatility Foundation Volatility Framework 2.5
LinuxUbuntu12_01x64 - A Profile for Linux Ubuntu12.01 x64
linux_banner               - Prints the Linux banner information
linux_yarascan             - A shell in the Linux memory image
[root@localhost volatility-master]#

But I can not find it.........

**Comment by npetroni** [comment]
I may be misunderstanding, but it looks like `LinuxUbuntu12_01x64` is in your grep output. Isn't that the profile you are looking for, or am I missing something? Try `--profile=LinuxUbuntu12_01x64` and see how it goes?

**Comment by gleeda** [comment]
Where is the zip file for the CentOS6.6 profile?  I don't see it in your `ls` output.

**Comment by iMHLv2** [comment]
I'm going to close this out, because it doesn't appear to be a bug in the framework. @JackNine - make sure you place the CentOS profile in the same directory as your Ubuntu profile. Don't try combining them into a single zip and make sure you don't have multiple Volatility installations that could be interfering with each other. Feel free to reopen if you're still having problems.
