### ISSUE TITLE
No suitable address space mapping found for Windows 7 image

### ISSUE THREAD

**Issue by itaykrk** [volatilityfoundation/volatility#324]
I've been trying to analyze Windows 7 memory dump which acquired using DumpIt.
The memory image size is 9GB. 
imageinfo output:
```
Suggested Profile(s) : Win2008R2SP0x64, Win7SP1x64, Win7SP0x64, Win2008R2SP1x64
AS Layer1 : WindowsAMD64PagedMemory (Kernel AS)
AS Layer2 : FileAddressSpace (memory.raw)
PAE type : No PAE
DTB : 0x187000L
KDBG : 0xf80002dff0f0L
Number of Processors : 1
Image Type (Service Pack) : 1
KPCR for CPU 0 : 0xfffff80002e00d00L
KUSER_SHARED_DATA : 0xfffff78000000000L
Image date and time : 2016-08-22 15:42:30 UTC+0000
Image local date and time : 2016-08-22 11:42:30 -0400
```
I've tried specifying kdbg and dtb but i keep getting:
`No suitable address space mapping found`

I used dumpIt on another windows 7 memory dump (4.5GB) and everything works fine.
Any suggestions?

**Comment by atcuno** [comment]
Hey,

Dumpit is broken on Windows 7 and beyond. Can you try acquiring with a
different tool?

Thanks,
Andrew (@attrc)

**Comment by itaykrk** [comment]
Which free tool you recommend for windows 7 and beyond?

**Comment by atcuno** [comment]
Unfortunately, none of the free tools are very stable at this point.

Thanks,
Andrew (@attrc)

**Comment by itaykrk** [comment]
so what is the most reliable commercial tool today?

**Comment by iMHLv2** [comment]
Sorry for the delay, we try not to show favoritism toward specific commercial tools on the open source forum. Feel free to send us an email: andrew @ memoryanalysis [dot] net or michael @ memoryanalysis [dot] net and we can provide a couple suggestions. Thanks!

**Comment by moha19** [comment]
Hi to all,
I dumped the raw dump memory of a Windows 10 pro x64 that was running on a 8 GB RAM by "ftk imager". I use volatility 2.5 standalone but **it doesn't work either command "imageinfo"**. help me ...

**Comment by npetroni** [comment]
Hi,

This issue has been closed. Please create a new issue for new topics.

There have been several improvements to Volatility related to Windows 10 since 2.5 standalone was released. Please try the latest master version (you'll need to install dependencies as well). https://github.com/volatilityfoundation/volatility/archive/master.zip

Note that there are 3 profiles for Windows 10 x64:
Win10x64
Win10x64_1AC738FB
Win10x64_DD08DD42

If it's fully patched, you'll probably find Win10x64_DD08DD42 works best.
