### ISSUE TITLE
Issue in extracting registry hives (Windows 2012 R2)

### ISSUE THREAD

**Issue by javariya** [volatilityfoundation/volatility#329]
Hi All
I have captured memory image of windows 2012 server using RamCapture. The following commands gives these results:
1. hivelist (empty)
2. hivescan (extracts physical addresses from local machine but does not extract results from amazon cloud machine)
3. Lsadump ( empty)
And all other commands related to registries extract no results.
What could be the possible reason? If I am doing something wrong. Though I have noticed hivelist somehow works for windows server 2008.

**Comment by npetroni** [comment]
Hi,

Which version of Volatility are you using? I believe we addressed most of these issues with a few recent commits. Can you try the latest master (https://github.com/volatilityfoundation/volatility/archive/master.zip) and use `--profile=Win2012R2x64_54B5A1C6`?

Also, can you post the specific version of 2012 server you are running?

Thanks

**Comment by javariya** [comment]
Hi npetroni
I am running Windows Server 2012 R2 and I am using volatility 2.5 standalone version. I always give it the profile part before the "_" part you mentioned that is --profile=Win2012R2x64. Does this volatility master have the direct .exe/ packaged version or I have to install the distorm3 and stuff required for it?  
Regards

**Comment by npetroni** [comment]
Sorry, `master` refers to the latest development version, not a stable release. You are right, you'd need to install the dependencies to get it working, including distorm3.

`Win2012R2x64_54B5A1C6` is a new profile that was added since the 2.5 standalone release. Please specify the full name to `--profile`.

**Comment by javariya** [comment]
Ok I will let you know after trying the new profile in 2.5 standalone and master as well. Another thought passed my mind, do the changes in security permissions have any effect on extraction of registry hives?

**Comment by javariya** [comment]
Hi 
I have tried using new profile in volatility 2.5 standalone version, it said its not a valid profile. 
I have installed the dependencies and tried to run the master but it gives errors as in the screenshot attached. By these errors I do get an idea that one or two dependencies are not installed correctly. I have followed all instructions but still i am unable to figure out why it is so.
![image](https://cloud.githubusercontent.com/assets/22416340/18861531/6248a684-849f-11e6-835f-9faf00654376.png)

**Comment by npetroni** [comment]
The standalone version will not work, that's why we need master.

Yeah, it looks like you are missing distorm3, which is a key dependency. You should also install pycrypto. Assuming you are on a 64-bit version of Windows, try these:
http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win-amd64-py2.7.exe
https://github.com/gdabah/distorm/releases/download/v3.3.4/distorm3-3.3.4.win-amd64.exe

There are 32-bit versions in the same directories.

Finally, I suggest using `--profile=Win2012R2x64_54B5A1C6`, assuming it's the same image we have been discussing.

**Comment by javariya** [comment]
Thank you so much @npetroni  now it is working and extracting all registry related artifacts. Yes I was using 64-bit OS.
Cheers :)

**Comment by iMHLv2** [comment]
Glad you're all set, thanks for the update!
