### ISSUE TITLE
RuntimeError: Vad tree too deep - something went wrong! 

### ISSUE THREAD

**Issue by dnice77** [volatilityfoundation/volatility#380]
Good morning,

I noticed when I was attempting to use the malfind or timeliner plugins the above error occurs. If there's any kind of additional output you need me to provide you, please let me know.

Thanks!

**Comment by gleeda** [comment]
Thank you for reporting this!  This can often happen, if there's a cycle in the tree.  Sometimes this is due to an errant acquisition.  

Just making a note for myself, we check that a tree is no taller than 100 nodes, but we actually have the tree height at `eproc.VadRoot.DepthOfTree`... I wonder if we should utilize this instead...

We might want to add a try/except to catch this error, so that we can skip to the next process, instead of hard stopping, however...

**Comment by op7ic** [comment]
Hi guys, I came across this today as well. I`m looking at big memory dump for windows 10 system with 16GB ram (--profile=Win10x64_10586). doing simple VAD dump results in "RuntimeError: Vad tree too deep - something went wrong!". 

In theory I could edit the source to either change value 100 to say 500 but I don't think its proper fix. Out of curiocity is there a reason for value 100 ?

**Comment by atcuno** [comment]
@op7ic once that level of recursion is hit we know something is off.

You can do per-process analysis to grab the particular VADs and avoid the broken one.

**Comment by op7ic** [comment]
@atcuno so hard limit was set to 100, is there reason for that? I thought that the whole idea is that you can walk the tree to work out its size ?
