### ISSUE TITLE
how to get version and kernal information of linux from module.dwarf(Linux profile) file

### ISSUE THREAD

**Issue by AnkitKundariya** [volatilityfoundation/volatility#389]
hello friends please anyone suggest me any solution for how to parse module.dwarf file and System.map-3.16.0-4-amd64 file to get  information about linux system version and kernel.
here i'm attaching a .zip file which contain both the file.

[Ubuntu1404(1).zip](https://github.com/volatilityfoundation/volatility/files/885230/Ubuntu1404.1.zip)

**Comment by bneuburg** [comment]
In case of Ubuntu profiles it is relatively easy since for each kernel update they ship a new System.map-$KERNELVERSION-$PATCHLEVEL file, so you can identify the exact kernel version by just looking at that string. 

Regarding the architecture (i.e. amd64 or x86) you could e.g. see if the symbol `init_level4_gpt` (then it is amd64) or `swapper_pg_dir` (then it is 32bit) is included in the System.map. However Volatility will detect the architecture for you if you put the profile in the correct place and run `./vol.py --info | grep Profile\ for\ Linux`. The last column of the output will tell you if it is x64 etc.

For the example you attached the kernel used seems to be 3.13.0-24 and it is a 32bit kernel.

Unfortunately the kernel version string and the distribution patch level are not included as a defined value in System.map or module.dwarf, so the best way to tackle this is probably to name the profile appropriately.

**Comment by atcuno** [comment]
Please let us know if you have further questions about this. I will close the issue in the meantime.
