### ISSUE TITLE
what is this?  i want solution

### ISSUE THREAD

**Issue by pjksss** [volatilityfoundation/volatility#426]
C:\volatility-2.6\volatility-master>python vol.py -h
Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 169, in main
    config.parse_options()
  File "C:\volatility-2.6\volatility-master\volatility\conf.py", line 262, in pa
rse_options
    self.optparser.print_help()
  File "C:\volatility-2.6\volatility-master\volatility\conf.py", line 97, in pri
nt_help
    optparse.OptionParser.print_help(self, file)
  File "C:\Python27\lib\optparse.py", line 1670, in print_help
    file.write(self.format_help().encode(encoding, "replace"))
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb9 in position 596: invalid
 start byte

**Comment by Signus** [comment]
I would advise that when submitting issues to public projects that you:

1. Submit relevant system information (OS, architecture, Python version, build number, branch or latest commit)
2. Show attempted solutions or relevant articles you feel may be relevant to the problem
3. Describe your issue in the description further, instead of being demanding

I would also suggest formatting any code blocks in issues for ease of use.

Which version of Windows are you currently using? It could be a small issue with your version or architecture, but ultimately `optparse` is deprecated and the library should be converted to `argparse` sometime in the future - I would imagine.

**Comment by gleeda** [comment]
@pjksss did you manage to get this working?  Did you have any other information if not?
