### ISSUE TITLE
Eventlogs command for Windows 10

### ISSUE THREAD

**Issue by VamosYoussef** [volatilityfoundation/volatility#446]
Hello guys, 

Does anyone know how to type in the eventlogs command on Windows 10 using volatility ?

Thank you!

**Comment by gleeda** [comment]
The `eventlogs` plugin doesn't work with newer Windows memory samples, because the event log format and how it's stored in memory has changed dramatically.  What we recommend you do in the meantime is use the `dumpfiles` plugin to extract the EVTX files and then parse those with something like https://github.com/williballenthin/EVTXtract or https://github.com/williballenthin/python-evtx etc..

**Comment by SamB** [comment]
Hmm.  If it were that simple, I could probably just read from the evtx on disk...

Looks like pull request #252 has some (reportedly) working code for extracting evtx from memory, but needs to be reworked a bit to use library code from the actual libraries instead of cloning it.

[Luckily, WinDbg's `!wmitrace.*` commands helped me pull the events I was looking for right out of the buffers where they had been stranded.]
