### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by DrDinosaur** [volatilityfoundation/volatility#587]
I'm not entirely sure if this is a Volatility or some issue on my end, but I'm trying to install volatility using PIP because I'm trying to make a plugin, but I can't seem to install it. 

Here is the package: https://pypi.org/project/volatility2/

I tried using Python 3.7 and using the ```--pre``` option in ```pip install```, but that didn't make a difference. I'm using Windows with Visual Studio. 

Here's the message I always get:
```
C:\Python27amd64>python.exe -m pip install volatility2
Collecting volatility2
  Could not find a version that satisfies the requirement volatility2 (from versions: )
No matching distribution found for volatility2
```

**Comment by iMHLv2** [comment]
Volatility currently requires Python 2, so it will not work with any Python 3 interpreters. I would also recommend just pulling down code from github rather than pip/pypi. That will get you the latest source code, which is what you want when writing plugins.  If you're on Windows and don't have git, you can try this: https://git-scm.com/download/win

**Comment by DrDinosaur** [comment]
I switched to a Linux environment and pulled from Github to get it working, but I'm still not sure why pip doesn't work. I guess you can close if you don't want to support that installation method.
