### ISSUE TITLE
A quick question about compiling the kernel

### ISSUE THREAD

**Issue by mntm** [volatilityfoundation/volatility#592]
Hi, I am working on android memory analysis now and I am facing a problem about the profile. 
I have the kernel from the manufacturer, the default .config  from the device and the exact toolchains. I followed the instructions in the wiki to build the profile (build the kernel, build LiME and finaly build the profile). During the kernel compilation, however, I made some corrections to the source code because it failed (nothing really important, just replacing  a #include <...> by #include "..."; and removed a deprecated perl notation). 
Now I am not sure if that could change something because when I use the profile to analyze a LiME dump, the latter is not recognized.
Could you tell me what I was doing wrong? 

Thank you

**Comment by pagabuc** [comment]
Hey mntm, when you built LiME and the profile did you "point" them to the compiled kernel? Otherwise, by default, they build against the kernel running on your machine, *not* against the one you compiled!
Another thing you can try is to set `timeout=0` when you `insmod` LiME.

A couple of moths ago I had a working environment for a goldfish kernel, so if you are still stuck write here!

**Comment by mntm** [comment]
Thank you for your answer. With goldfish, everything went well. I still don't understand why! I followed the same procedures but still not working on my devices.

**Comment by adesatriowirawan** [comment]
hey mntm, can i ask you about goldfish kernel?
