### ISSUE TITLE
I found that volatility could not fully identify the profile

### ISSUE THREAD

**Issue by wutong66** [volatilityfoundation/volatility#667]
I have two the virtual machine: ubuntu14045 and ubuntu 1204.But when I  run vol.py,volatility can only identify one of zip profile.what is  the problem?
![image](https://user-images.githubusercontent.com/28525117/69033289-a9f3aa80-0a19-11ea-8131-bad93ea5078d.png)
![image](https://user-images.githubusercontent.com/28525117/69033395-e4f5de00-0a19-11ea-9dd9-72de88c05282.png)
I hope you can help me

**Comment by atcuno** [comment]
Can you please paste the output of:

python vol.py --info | grep Linux

Also, what makes you think that both profiles are not identified?

**Comment by Season12345** [comment]
I will paste that later.Because the output is that found a dwarf but is a sysmap file or found a sysmap but is a dwarf file.



            
            
                
                    
                            
                                
                            
                            
                                739962856
                            
                    
                        
                            
                                    邮箱：739962856@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 11/18/2019 22:46, Andrew Case wrote: Can you please paste the output of:
python vol.py --info | grep Linux
Also, what makes you think that both profiles are not identified?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/volatilityfoundation/volatility/issues/667?email_source=notifications\u0026email_token=AGZUEPPHNL6SOEO2XV77HITQUKTFRA5CNFSM4JOPLG22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEKVLHI#issuecomment-555046301",
"url": "https://github.com/volatilityfoundation/volatility/issues/667?email_source=notifications\u0026email_token=AGZUEPPHNL6SOEO2XV77HITQUKTFRA5CNFSM4JOPLG22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEKVLHI#issuecomment-555046301",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Season12345** [comment]
> Can you please paste the output of:
> 
> python vol.py --info | grep Linux
> 
> Also, what makes you think that both profiles are not identified?
Hello,this is the output
![image](https://user-images.githubusercontent.com/28525117/69126531-65ccdc80-0ae3-11ea-8072-41b301d4fcac.png)
And for ubuntu14045,found the system file is module.dwarf but not the System.map.So I think it can't identify the System.map.
And for ubuntu1204,found the dwarf file is System.map but not the module.dwarf.So I think it can't identfy the module.dwarf.

**Comment by Season12345** [comment]
> Can you please paste the output of:
> 
> python vol.py --info | grep Linux
> 
> Also, what makes you think that both profiles are not identified?

Hello,this is the output
image
And for ubuntu14045,found the system file is module.dwarf but not the System.map.So I think it can't identify the System.map.
And for ubuntu1204,found the dwarf file is System.map but not the module.dwarf.So I think it can't identfy the module.dwarf.

**Comment by Season12345** [comment]
> Can you please paste the output of:
> 
> python vol.py --info | grep Linux
> 
> Also, what makes you think that both profiles are not identified?

Hello,this is the output
![image](https://user-images.githubusercontent.com/28525117/69126949-4da98d00-0ae4-11ea-8ad4-d05955d55768.png)
And for ubuntu14045,found the system file is module.dwarf but not the System.map.So I think it can't identify the System.map.
And for ubuntu1204,found the dwarf file is System.map but not the module.dwarf.So I think it can't identfy the module.dwarf.
