### ISSUE TITLE
volatility psscan output's Name is limit in 14 words?

### ISSUE THREAD

**Issue by yyl321** [volatilityfoundation/volatility#674]
When I user the psscan plugin, I found the output of Name is limit in 14 words , like this :
![微信图片_20191223114916](https://user-images.githubusercontent.com/35856462/71334707-3f82dc80-257a-11ea-870a-577278402d34.png)
So can you help me to fix the problems ? thank you

**Comment by gleeda** [comment]
It's a limitation of the structure that is used to get the process name, where it limited in the number of characters stored.  If you want to get the full name, you can use the `cmdline` plugin like so (just replace the bracketed items with the correct values):

```
$ python vol.py -f [MEMORY DUMP] --profile=[PROFILE] -o [OFFSET] cmdline -v
```

Since this isn't a volatility error, I'm going to close this issue for now.  Feel free to reopen if you have some other issue.
