### ISSUE TITLE
Passing command line arguments without any plugin

### ISSUE THREAD

**Issue by AqibMukhtar** [volatilityfoundation/volatility#705]
I am trying to add new functionality to volatility that is the automated acquisition of memory dumps from the VM. If I am creating a plugin for this functionality then I need to provide a memory dump (which in my case is not feasible because I am acquiring memory not analyzing it). The other option is to provide the command line argument to volatility in vol.py file and use it as we use --info argument. The issue with this approach is that I am unable to provide different parameters for my memory acquisition argument (let's say it is acqmem). My volatility command should look like this
python vol.py --acqmem -D path_to_save_memory_dumps -i time_interval_between_two_dumps
How can I achieve this goal?

**Comment by atcuno** [comment]
With the exception of old systems with FireWire and no DMA protection, Volatility is a tool for analysis only.

It seems like you could make a separate tool with more flexible options in order to acquire the sample and then feed to sample as -f to Volatility itself.

I am going to close this ticket, but feel free to reopen if I missed something.
