### ISSUE TITLE
Trying to find a profile for the OS of a 32GB .mem file with no luck.

### ISSUE THREAD

**Issue by Mazren79** [volatilityfoundation/volatility#727]
Hello, I'd like to start out with the fact that I'm new to this game so... please be gentle.

I downloaded the volatility_2.6_win64_standalone.exe as well as 2.7 phython.  I obtained the .mem from FTK Imager.  When I try:
 ...\volatility_2.6_win64_standalone>volatility.exe -f memdump.mem imageinfo > imageinfo.txt
I get:
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...

It spins and never produces a result.  I let it go for nearly 4hrs last night.  Is it because the .mem is to big?  I already know the OS is Win10, it's 64bit, and version 1903 (OS Build 18362.900), but I was trying to play with volatility because I'm new.  

Any help would be appreciated.

**Comment by AqibMukhtar** [comment]
What is size of your memory dump?

**Comment by atcuno** [comment]
Hello @Mazren79 ,

The standalone version of Volatility is quite old now (many years). To analyze that version of Windows, you want to use the latest source code checkout from GitHub (here).

You can then use --profile=Win10x64_18362 in order to analyze the sample.

With that said, FTK imager is not a stable acquisition tool and often produces corrupt memory captures. Is the system you are acquiring from bare metal or is it a virtual machine guest?

**Comment by Mazren79** [comment]
Hello @atcuno, It's my desktop, not virtual.  I've just downloaded the source code version and I'll try it out.  I've been led to believe that 32GB is a bit much for volatility.  Is this true?  As for acquisition, which tool would you recommend over FTK imager?

**Comment by atcuno** [comment]
It is definitely not too much. We have successfully analyzed samples of 128GB, 256GB, and beyond.

For real-world investigations, Surge is the only tool we trust: https://www.volexity.com/products-overview/surge/

For R&D purposes, we recommend virtual machines, such as VMWare, and then using the built-in facilities to acquire memory from the guest.
