### ISSUE TITLE
What does this mean in Volatility prefetchparser reading

### ISSUE THREAD

**Issue by pundittech** [volatilityfoundation/volatility#754]
G'day,

I am really sorry for putting this on here but I have no idea where else to post this for an answer. If you could please help me with this query I would be really grateful. 

I currently have installed prefetchparser plugin and have executed this without any issues.  
However, for one particular file, NOTEPAD.EXE I am getting this weird 6..0 next to the Run Times field. Could you please interpret what Volatility is telling me? Is it saying it has been run 6 times? I am pretty sure I did but what is the ..0 that follows the 6?

![Screenshot from 2020-09-17 10-48-52](https://user-images.githubusercontent.com/49902136/93406829-02166a00-f8d4-11ea-9679-09d393dc9e76.png)

**Comment by ikelos** [comment]
Hi there, I'm pretty sure this is a volatility 2 question, and the `...` is because the number is too large to fit in the column width.  So it's actually a number that starts with 6 and ends with 0 but will have four or more digits in between which would break the formatting.  You can see what the values would be by outputting the results as CSV or some other data format, but the default display elides values that are too long to ensure the formatting doesn't break.  Hope this answers your question?  I'm going to mark this as closed, but feel free to reopen it if that didn't answer it for you...  5:)

**Comment by pundittech** [comment]
Thank you so much. Although I have literally only run NOTEPAD maybe a handful of times.This is a new VM with an downloaded ISO. I will however dump this on to CSV for a further look just to quench my curiousity.
Thank you so much ikelos for replying to this.

**Comment by beena113** [comment]
@ikelos  Sir, I am working on a project where I have to analyze LiME memory dump using volatility tool. When I try to load module it shows "Exec format error". Even after trying for so long, I still am not able to remove this error. Can you please do me a favor and send me sample RAM dump with .lime extension so that I can use volatility tool for analysis. I will be very grateful to you.

**Comment by ikelos** [comment]
@beena113, please open a separate issue or contact us on slack.  This issue is specifically about a volatility 2 issue and has already been closed.

**Comment by beena113** [comment]
I only commented there just to mention you. Please accept my apologies if it cause any discomfort.
RegardsMubeena
    On Thursday, January 7, 2021, 02:34:04 AM GMT+5, ikelos <notifications@github.com> wrote:  
 
 


@beena113, please open a separate issue or contact us on slack. This issue is specifically about a volatility 2 issue and has already been closed.

**Comment by ikelos** [comment]
It's fine, I'd just prefer to prevent the issue tracker becoming a place for discussions.  [Slack](https://www.volatilityfoundation.org/slack) is definitely the place for such discussions, and I get any messages left for me on there too...  5:)
