### ISSUE TITLE
I have with add new plugins volatility2.6 .

### ISSUE THREAD

**Issue by LeviathanGod** [volatilityfoundation/volatility#856]
Hi
when i run volatility-plugins i have problem with Volatility Foundation Volatility Framework 2.6
*** Failed to import volatility.plugins.chromehistory (ImportError: No module named csv)
*** Failed to import volatility.plugins.firefoxhistory (ImportError: No module named csv)
ERROR : volatility.debug : You must specify something to do (try -h)
this my command:./volatility_2.6_lin64_standalone –plugins=volatility-plugins/ -f dump.raw –profile=Win7SP1x64 chromehistory
Thanks you.
I apologize for not asking in volatility 2.6

**Comment by ikelos** [comment]
I'm afraid that volatility 2 does not appear to under active development anymore, however the error message (`No module named csv`) suggests that the version of python in use is lacking the [standard csv library](https://docs.python.org/2/library/csv.html) for some reason.  This is therefore not a volatility issue, but an issue with the python distribution in use.  Since the python2 page also points out that python 2 is no longer supported, I would strongly recommend trying to make use of python 3/volatility 3.

So the recommended courses of action are:

* Check the python 2 installation and determine why the standard csv module is not present/cannot be imported by volatility 2
* Either attempt to port the chromehistory plugin, or request on the vol3 bug tracker that the it be ported across for you (although this will depend on a volunteer finding time and stepping up to complete the request).

As this is not a volatility 2 bug, I'm going to close off this issue.  Please feel free to reopen it if you feel the issue is specific to volatility 2 and can demonstrate evidence that the python2 installation is functioning correctly with all standard libraries.
